---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hendrix
description: Blue-Build Recipe based on Bluefin

base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: 42 

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    optfix:
      - enpass
    repos:
      files:
        - https://yum.enpass.io/enpass-yum.repo
      copr:
        - scottames/ghostty
        - wojnilowicz/ungoogled-chromium
    install:
      packages:
        - ghostty
        - enpass
        - ungoogled-chromium
        - openh264
        - zsh
    remove:
      packages:
        - distrobox
        - fish # Will be added via brew later, otherwise completions etc. will not be taken care of by brew

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

