---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hendrix
description: Blue-Build Recipe based on Bluefin

base-image: ghcr.io/ublue-os/bluefin-dx-nvidia-open
image-version: 42 

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    optfix:
      - enpass
    repos:
      files:
        - https://yum.enpass.io/enpass-yum.repo
      copr:
        - scottames/ghostty
        - wojnilowicz/ungoogled-chromium
    install:
      packages:
        - ghostty
        - enpass
        - ungoogled-chromium
    remove:
      packages:
        - distrobox

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

